/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/**
 * @deprecated
 */
export declare function isHiddenFile(filePath: string): boolean
export declare function isHiddenFileWin32(filePath: string): boolean
/**
 * @deprecated
 */
export declare function isHiddenFileWin322(filePath: string): boolean
